name: customer_portal
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase (latest compatible)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Other deps
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  const_date_time: ^1.1.0
  getter: ^0.0.3
  pdf: ^3.11.0
  pdf_viewer_plugin: ^2.0.1
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.3.0
  flutter_email_sender: ^6.0.3
  google_sign_in: ^6.2.1
  printing: ^5.13.1
  secondsplash: ^1.0.0
  duration: ^4.0.3
  fl_chart: ^0.68.0
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
