// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUIpwgtl5q1XPSs8bzwBaeWbo0z00RBtc',
    appId: '1:834730152064:web:7ffab1e6c97b0efb185665',
    messagingSenderId: '834730152064',
    projectId: 'customer-portal-c9b8e',
    authDomain: 'customer-portal-c9b8e.firebaseapp.com',
    storageBucket: 'customer-portal-c9b8e.appspot.com',
    measurementId: 'G-B97NYRRM75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv_IDmx62qbrWLfSUXvN9lxAi7w3MCrIs',
    appId: '1:834730152064:android:ca4e7fe14122e33b185665',
    messagingSenderId: '834730152064',
    projectId: 'customer-portal-c9b8e',
    storageBucket: 'customer-portal-c9b8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArEYKpDc5zYgDj3U_1gUcYorMxcT0kSbE',
    appId: '1:834730152064:ios:b85794855d0cbe77185665',
    messagingSenderId: '834730152064',
    projectId: 'customer-portal-c9b8e',
    storageBucket: 'customer-portal-c9b8e.appspot.com',
    iosBundleId: 'com.example.customerPortal',
  );
}
