import 'package:customer_portal/pages/InvoiceListScreen.dart';
import 'package:flutter/material.dart';
// ignore: depend_on_referenced_packages
import 'package:flutter_localizations/flutter_localizations.dart'; // This import is crucial
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure you have this file for Firebase configuration
import 'language_provider.dart'; // Ensure this file exists for language management
import 'generated/l10n.dart'; // Ensure this file exists and is generated by the localization setup

import 'pages/example_screen.dart'; // Example screen for additional routing
import 'pages/login.page.dart';
import 'pages/signup.page.dart';
import 'pages/dashboard.dart';
import 'pages/customer_registration_screen.dart';
import 'pages/installment_plan_screen.dart';
import 'pages/payment_log_screen.dart';
import 'splash_screen.dart';
import 'screens/app_settings_screen.dart';
import 'screens/customer_support_screen.dart';
import 'screens/edit_profile_screen.dart';
import 'screens/notifications_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/rate_us_screen.dart';
import 'screens/terms_conditions_screen.dart';
import 'language_screen.dart'; // Screen for language selection

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    ChangeNotifierProvider(
      create: (_) => LanguageProvider(),
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer<LanguageProvider>(
      builder: (context, languageProvider, child) {
        return MaterialApp(
          title: 'Customer Portal',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          locale: languageProvider.locale,
          supportedLocales: S.delegate.supportedLocales,
          localizationsDelegates: [
            S.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          home: const SplashScreen(),
          routes: {
            '/login': (context) => const LoginPage(),
            '/signup': (context) => const SignupPage(),
            '/dashboard': (context) => AccountDashboardScreen(),
            '/installment_plan': (context) => const InstallmentPlanScreen(),
            '/payment_log': (context) => PaymentLogScreen(),
            '/register_customer': (context) => CustomerRegistrationScreen(),
            '/app_settings': (context) => AppSettingsScreen(),
            '/customer_support': (context) => CustomerSupportScreen(),
            '/edit_profile': (context) => EditProfileScreen(),
            '/languages': (context) => LanguagesScreen(),
            '/notifications': (context) => NotificationsScreen(),
            '/profile': (context) => ProfileScreen(),
            '/rate_us': (context) => RateUsScreen(),
            '/terms_conditions': (context) => TermsConditionsScreen(),
            '/registration': (context) => CustomerRegistrationScreen(),
            '/example': (context) => ExampleScreen(),
            '/invoice_list': (context) => InvoiceListScreen(),
          },
          debugShowCheckedModeBanner:
              false, // Add this line to remove the debug banner
        );
      },
    );
  }
}
