import 'package:customer_portal/pages/InvoiceListScreen.dart';
import 'package:flutter/material.dart';
// ignore: depend_on_referenced_packages
import 'package:flutter_localizations/flutter_localizations.dart'; // This import is crucial
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure you have this file for Firebase configuration
import 'language_provider.dart'; // Ensure this file exists for language management
import 'generated/l10n.dart'; // Ensure this file exists and is generated by the localization setup
import 'screens/terms_conditions_screen.dart';
import 'language_screen.dart'; // Screen for language selection

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    ChangeNotifierProvider(
      create: (_) => LanguageProvider(),
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer<LanguageProvider>(
      builder: (context, languageProvider, child) {
        return MaterialApp(
          title: 'Customer Portal',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          locale: languageProvider.locale,
          supportedLocales: S.delegate.supportedLocales,
          localizationsDelegates: [
            S.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          home: const SplashScreen(),
          routes: {
            '/login': (context) => const LoginPage(),
            '/signup': (context) => const SignupPage(),
            '/dashboard': (context) => AccountDashboardScreen(),
            '/installment_plan': (context) => const InstallmentPlanScreen(),
            '/payment_log': (context) => PaymentLogScreen(),
            '/register_customer': (context) => CustomerRegistrationScreen(),
  
            '/example': (context) => ExampleScreen(),
            '/invoice_list': (context) => InvoiceListScreen(),
          },
          debugShowCheckedModeBanner:
              false, // Add this line to remove the debug banner
        );
      },
    );
  }
}
